export AWS_REGION="${aws_region}"
export CLUSTER_NAME="${cluster_name}"
export NODEPOOL_NAME="${nodepool_name}"
export CONTROL_PLANE_SUBNETS="%{ for subnet_id in private_subnet_ids ~} ${subnet_id},%{ endfor ~}"
export VPC_ID="${vpc_id}"
export podAddressCidrBlocks="10.2.0.0/16"
export serviceAddressCidrBlocks="10.1.0.0/16"
export PUBLIC_SERVICE_SUBNET="%{ for subnet_id in public_subnet_ids ~} ${subnet_id},%{ endfor ~}"
export DB_KMS_KEY_ARN="${dbs_kms_key_arn}"
export CONTROL_PLANE_PROFILE="${control_plane_profile}"
export SSH_KEY_PAIR_NAME="${ssh_key_pair_name}"
export BASTION_IP="${bastion_address}"
export API_ROLE_ARN="${api_role_arn}"
export NODEPOOL_PROFILE="${nodepool_profile}"
export NODEPOOL_SUBNET="${nodepool_subnet_id}"
export SSH_PRIVATE_KEY="${ssh_private_key_path}"

